spring.application.name=WEB
# ?????????? ???? ? ???? (???????? ???????)
spring.datasource.url=jdbc:h2:file:./data/cinema_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# --- ???? ???????????? (????????? 3) ---

# 1. ???????????? ????????? (?????? INFO ? ???????)
logging.level.com.cinema=INFO

# 2. ???? ???????? ???????????? (??????? ?? ????????? API)
# ???? false - API ?????????? ???????? ??????
cinema.security.allow-delete=true
# ????: ?????? ?? ????????? ???????????? (true/false)
cinema.security.allow-user-delete=true

cinema.security.allow-movie-delete=true